path: /content/ordered_dataset
train: /content/ordered_dataset/train
val: /content/ordered_dataset/val
test: /content/ordered_dataset/test
nc: 16
names:
  0: no passing
  1: stop
  2: no stop or parking
  3: no parking
  4: no vehicles
  5: vehicle no turn right
  6: vehicle no turn left
  7: pedestrians
  8: keep right
  9: keep left
  10: keep straight
  11: no turn left
  12: no turn right
  13: pedestrians (warning)
  14: children crossing
  15: cross with priority road
