path: /content/repository_name
train: /data/images
val: /data/images

names:
  0: no passing
  1: stop
  2: no stop or parking
  3: no parking
  4: no vehicles
  5: vehicle no turn right
  6: vehicle no turn left
  7: pedestrians
  8: keep right
  9: keep left
  10: keep straight
  11: no turn left
  12: no turn right
  13: pedestrians (warning)
  14: children crossing
  15: cross with priority road
  
